# Generated by Django 4.0.6 on 2022-07-27 14:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('slug', 'author')},
        ),
    ]
